version: '2'
services:
  
  # Profile pictures
  db:
    image: mongo:3.3
    container_name: profilepicture-db
    ports:
      - "3008:27017"
    volumes:
      - ./backup:/backup:rw

  profilepictures:
    image: fullhd4knofake/1a_profilepictures
    container_name: profilepictures-ms
    depends_on:
      - db
    links:
      - db
    environment:
      VIRTUAL_HOST: profilepictures.local
    ports:
      - "3003:8080"
    depends_on:
      - db

  # Bicicletas
  bicicletasdb:
    image: mysql:5.7
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: diego
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: bicicletasdb
      MYSQL_HOST: bicicletasdb
  biciun:
    image: fullhd4knofake/bicicletas
    ports:
      - "3004:9002"
    depends_on:
      - bicicletasdb

  # Usuarios
  users-db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: users
      MYSQL_HOST: users-db
  users-ms:
    image: fullhd4knofake/usuarios
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - "3001:3001"
    depends_on:
      - users-db

  # Historial de prestamos
  historial-db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: asdf
      MYSQL_USER: juancho
      MYSQL_PASSWORD: asdf
      MYSQL_DATABASE: historial
      MYSQL_HOST: historial-db
  historial-ms:
    image: fullhd4knofake/historial
    ports:
      - "3002:9001"
    depends_on:
      - historial-db
  
  # Tokens
  1a_login_ms:
    image: fullhd4knofake/1a_login_ms
    ports:
     - "3005:5000"
    depends_on:
     - 1a_login_db
  1a_login_db:
    image: mysql:5.7
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: alejo
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: users
      MYSQL_HOST: 1a_login_db

  biciun-ldap:
    image: osixia/openldap:1.1.8
    container_name: biciun-ldap
    environment:
      COMPOSE_HTTP_TIMEOUT: 200
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Biciun UNAL"
      LDAP_DOMAIN: "biciun.unal.edu.co"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    hostname: "arqsoft.org"
    
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "biciun-ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8085:80"
    links:
      - biciun-ldap

  # Api Gateway
  biciun-api:
    image: fullhd4knofake/api-gateway
    environment:
      PORT: '4500'
      SHOW_URLS: 'true'

      USERS_URL: 'users-ms'
      USERS_PORT: '3001'
      USERS_ENTRY: 'users/'
      
      PRESTAMOS_URL: 'historial-ms'
      PRESTAMOS_PORT: '9001'
      PRESTAMOS_ENTRY: 'prestamos'
      
      PROFILES_PHOTOS_URL: 'profilepictures'
      PROFILES_PHOTOS_PORT: '8080'
      PROFILES_PHOTOS_ENTRY: 'profilepictures'
      
      LOGIN_URL: '1a_login_ms'
      LOGIN_PORT: '5000'
      LOGIN_ENTRY: 'login'

      BICICLETAS_URL: 'biciun'
      BICICLETAS_PORT: '9002'
      BICICLETAS_ENTRY: 'bicicletas'

      AUTH_URL: 
      AUTH_PORT: '3001'
      AUTH_ENTRY: 'ldap/'

    ports:
      - '4500:4500'
    depends_on:
      - historial-db
      - historial-ms
      - users-db
      - users-ms
      - bicicletasdb
      - biciun
      - profilepictures
      - db

  biciun-proxy:
    image: fullhd4knofake/proxy
    ports:
      - "80:80"
    depends_on: 
      - biciun-api