version: '2'
services:
  biciun-proxy:
    scale: 1
    start_on_create: true
  users-ms:
    scale: 1
    start_on_create: true
  bicicletasdb:
    scale: 1
    start_on_create: true
  historial-ms:
    scale: 1
    start_on_create: true
  biciun:
    scale: 1
    start_on_create: true
  biciun-ldap:
    scale: 1
    start_on_create: true
  users-db:
    scale: 1
    start_on_create: true
  phpldapadmin:
    scale: 1
    start_on_create: true
  historial-db:
    scale: 1
    start_on_create: true
  biciun-api:
    scale: 1
    start_on_create: true